/**
 * Sample card catalog for CardScout.
 *
 * Names, set codes, and collector numbers match the public Pokémon TCG dataset
 * (https://github.com/PokemonTCG/pokemon-tcg-data). Pictures are the matching
 * files on images.pokemontcg.io.
 *
 * Prices are rounded practice estimates in USD so every screen works with no
 * API key. They are not live shop quotes. Values expands each card into
 * sample TCGPlayer, PriceCharting, and eBay sold boxes (see sample-sources.ts).
 *
 * Evolving Skies #215 is the alternate-art Umbreon VMAX. The public JSON file
 * labels both #214 and #215 as "Rare Rainbow"; #214 is the rainbow rare and
 * #215 is the moonlit alternate art, so this catalog says Alternate Art.
 */

export interface SampleCard {
  id: string;
  name: string;
  setName: string;
  setId: string;
  numberLabel: string;
  rarity: string;
  imageUrl: string;
  marketPrice: number;
  lowPrice: number;
  highPrice: number;
  /** Sample asking price. Omit when the card is lookup-only. */
  ask?: number;
  seller?: string;
}

function art(setId: string, number: string): string {
  return `https://images.pokemontcg.io/${setId}/${number}.png`;
}

export const SAMPLE_CARDS: SampleCard[] = [
  {
    id: "base1-4",
    name: "Charizard",
    setName: "Base",
    setId: "base1",
    numberLabel: "4/102",
    rarity: "Rare Holo",
    imageUrl: art("base1", "4"),
    marketPrice: 450,
    lowPrice: 360,
    highPrice: 640,
    ask: 329,
    seller: "Lakeside Cards",
  },
  {
    id: "base1-58",
    name: "Pikachu",
    setName: "Base",
    setId: "base1",
    numberLabel: "58/102",
    rarity: "Common",
    imageUrl: art("base1", "58"),
    marketPrice: 18,
    lowPrice: 12,
    highPrice: 30,
    ask: 11,
    seller: "Binder Club",
  },
  {
    id: "base1-2",
    name: "Blastoise",
    setName: "Base",
    setId: "base1",
    numberLabel: "2/102",
    rarity: "Rare Holo",
    imageUrl: art("base1", "2"),
    marketPrice: 190,
    lowPrice: 150,
    highPrice: 280,
    ask: 149,
    seller: "Night Market",
  },
  {
    id: "base1-15",
    name: "Venusaur",
    setName: "Base",
    setId: "base1",
    numberLabel: "15/102",
    rarity: "Rare Holo",
    imageUrl: art("base1", "15"),
    marketPrice: 145,
    lowPrice: 110,
    highPrice: 210,
  },
  {
    id: "swsh4-188",
    name: "Pikachu VMAX",
    setName: "Vivid Voltage",
    setId: "swsh4",
    numberLabel: "188/185",
    rarity: "Rainbow Rare",
    imageUrl: art("swsh4", "188"),
    marketPrice: 36,
    lowPrice: 27,
    highPrice: 58,
    ask: 25,
    seller: "Holo Desk",
  },
  {
    id: "swsh7-215",
    name: "Umbreon VMAX",
    setName: "Evolving Skies",
    setId: "swsh7",
    numberLabel: "215/203",
    rarity: "Alternate Art",
    imageUrl: art("swsh7", "215"),
    marketPrice: 980,
    lowPrice: 820,
    highPrice: 1450,
    ask: 725,
    seller: "Route 4 Games",
  },
  {
    id: "swsh12pt5gg-GG30",
    name: "Pikachu",
    setName: "Crown Zenith",
    setId: "swsh12pt5gg",
    numberLabel: "GG30/GG70",
    rarity: "Galarian Gallery",
    imageUrl: art("swsh12pt5gg", "GG30"),
    marketPrice: 22,
    lowPrice: 16,
    highPrice: 36,
    ask: 14,
    seller: "Maple City Cards",
  },
  {
    id: "sv3-125",
    name: "Charizard ex",
    setName: "Obsidian Flames",
    setId: "sv3",
    numberLabel: "125/197",
    rarity: "Double Rare",
    imageUrl: art("sv3", "125"),
    marketPrice: 11,
    lowPrice: 8,
    highPrice: 16,
    ask: 7.5,
    seller: "Holo Desk",
  },
  {
    id: "sv3-223",
    name: "Charizard ex",
    setName: "Obsidian Flames",
    setId: "sv3",
    numberLabel: "223/197",
    rarity: "Special Illustration Rare",
    imageUrl: art("sv3", "223"),
    marketPrice: 240,
    lowPrice: 190,
    highPrice: 330,
    ask: 168,
    seller: "Route 4 Games",
  },
  {
    id: "sv3-228",
    name: "Charizard ex",
    setName: "Obsidian Flames",
    setId: "sv3",
    numberLabel: "228/197",
    rarity: "Hyper Rare",
    imageUrl: art("sv3", "228"),
    marketPrice: 95,
    lowPrice: 75,
    highPrice: 140,
    ask: 69,
    seller: "Saturday Swap",
  },
  {
    id: "sv3pt5-6",
    name: "Charizard ex",
    setName: "151",
    setId: "sv3pt5",
    numberLabel: "6/165",
    rarity: "Double Rare",
    imageUrl: art("sv3pt5", "6"),
    marketPrice: 6.5,
    lowPrice: 4.5,
    highPrice: 10,
    ask: 4.75,
    seller: "Pocket League",
  },
  {
    id: "sv3pt5-25",
    name: "Pikachu",
    setName: "151",
    setId: "sv3pt5",
    numberLabel: "25/165",
    rarity: "Common",
    imageUrl: art("sv3pt5", "25"),
    marketPrice: 0.75,
    lowPrice: 0.25,
    highPrice: 2,
  },
  {
    id: "sv3pt5-151",
    name: "Mew ex",
    setName: "151",
    setId: "sv3pt5",
    numberLabel: "151/165",
    rarity: "Double Rare",
    imageUrl: art("sv3pt5", "151"),
    marketPrice: 9,
    lowPrice: 6,
    highPrice: 14,
  },
  {
    id: "sv3pt5-173",
    name: "Pikachu",
    setName: "151",
    setId: "sv3pt5",
    numberLabel: "173/165",
    rarity: "Illustration Rare",
    imageUrl: art("sv3pt5", "173"),
    marketPrice: 14,
    lowPrice: 10,
    highPrice: 22,
    ask: 9,
    seller: "Maple City Cards",
  },
  {
    id: "sv3pt5-199",
    name: "Charizard ex",
    setName: "151",
    setId: "sv3pt5",
    numberLabel: "199/165",
    rarity: "Special Illustration Rare",
    imageUrl: art("sv3pt5", "199"),
    marketPrice: 175,
    lowPrice: 140,
    highPrice: 240,
    ask: 126,
    seller: "Pocket League",
  },
  {
    id: "sv4pt5-232",
    name: "Mew ex",
    setName: "Paldean Fates",
    setId: "sv4pt5",
    numberLabel: "232/91",
    rarity: "Special Illustration Rare",
    imageUrl: art("sv4pt5", "232"),
    marketPrice: 310,
    lowPrice: 250,
    highPrice: 430,
    ask: 229,
    seller: "Saturday Swap",
  },
  {
    id: "sv4pt5-233",
    name: "Gardevoir ex",
    setName: "Paldean Fates",
    setId: "sv4pt5",
    numberLabel: "233/91",
    rarity: "Special Illustration Rare",
    imageUrl: art("sv4pt5", "233"),
    marketPrice: 115,
    lowPrice: 90,
    highPrice: 165,
    ask: 84,
    seller: "Lakeside Cards",
  },
  {
    id: "sv4pt5-234",
    name: "Charizard ex",
    setName: "Paldean Fates",
    setId: "sv4pt5",
    numberLabel: "234/91",
    rarity: "Special Illustration Rare",
    imageUrl: art("sv4pt5", "234"),
    marketPrice: 62,
    lowPrice: 48,
    highPrice: 95,
    ask: 45,
    seller: "Night Market",
  },
  {
    id: "sv4pt5-237",
    name: "Iono",
    setName: "Paldean Fates",
    setId: "sv4pt5",
    numberLabel: "237/91",
    rarity: "Special Illustration Rare",
    imageUrl: art("sv4pt5", "237"),
    marketPrice: 88,
    lowPrice: 68,
    highPrice: 130,
    ask: 63,
    seller: "Binder Club",
  },
  {
    id: "sv8-57",
    name: "Pikachu ex",
    setName: "Surging Sparks",
    setId: "sv8",
    numberLabel: "57/191",
    rarity: "Double Rare",
    imageUrl: art("sv8", "57"),
    marketPrice: 4,
    lowPrice: 2.5,
    highPrice: 7,
  },
  {
    id: "sv8-238",
    name: "Pikachu ex",
    setName: "Surging Sparks",
    setId: "sv8",
    numberLabel: "238/191",
    rarity: "Special Illustration Rare",
    imageUrl: art("sv8", "238"),
    marketPrice: 165,
    lowPrice: 130,
    highPrice: 230,
    ask: 118,
    seller: "Holo Desk",
  },
  {
    id: "sv8pt5-60",
    name: "Umbreon ex",
    setName: "Prismatic Evolutions",
    setId: "sv8pt5",
    numberLabel: "60/131",
    rarity: "Double Rare",
    imageUrl: art("sv8pt5", "60"),
    marketPrice: 5.5,
    lowPrice: 3.5,
    highPrice: 9,
  },
  {
    id: "sv8pt5-156",
    name: "Sylveon ex",
    setName: "Prismatic Evolutions",
    setId: "sv8pt5",
    numberLabel: "156/131",
    rarity: "Special Illustration Rare",
    imageUrl: art("sv8pt5", "156"),
    marketPrice: 195,
    lowPrice: 150,
    highPrice: 280,
    ask: 139,
    seller: "Saturday Swap",
  },
  {
    id: "sv8pt5-161",
    name: "Umbreon ex",
    setName: "Prismatic Evolutions",
    setId: "sv8pt5",
    numberLabel: "161/131",
    rarity: "Special Illustration Rare",
    imageUrl: art("sv8pt5", "161"),
    marketPrice: 540,
    lowPrice: 430,
    highPrice: 790,
    ask: 389,
    seller: "Pocket League",
  },
  {
    id: "sv8pt5-167",
    name: "Eevee ex",
    setName: "Prismatic Evolutions",
    setId: "sv8pt5",
    numberLabel: "167/131",
    rarity: "Special Illustration Rare",
    imageUrl: art("sv8pt5", "167"),
    marketPrice: 78,
    lowPrice: 60,
    highPrice: 115,
    ask: 54,
    seller: "Maple City Cards",
  },
  {
    id: "sv10-231",
    name: "Team Rocket's Mewtwo ex",
    setName: "Destined Rivals",
    setId: "sv10",
    numberLabel: "231/182",
    rarity: "Special Illustration Rare",
    imageUrl: art("sv10", "231"),
    marketPrice: 130,
    lowPrice: 100,
    highPrice: 185,
    ask: 89,
    seller: "Lakeside Cards",
  },
  {
    id: "me1-178",
    name: "Mega Gardevoir ex",
    setName: "Mega Evolution",
    setId: "me1",
    numberLabel: "178/132",
    rarity: "Special Illustration Rare",
    imageUrl: art("me1", "178"),
    marketPrice: 72,
    lowPrice: 55,
    highPrice: 110,
    ask: 51,
    seller: "Night Market",
  },
  {
    id: "me2-13",
    name: "Mega Charizard X ex",
    setName: "Phantasmal Flames",
    setId: "me2",
    numberLabel: "13/94",
    rarity: "Double Rare",
    imageUrl: art("me2", "13"),
    marketPrice: 9.5,
    lowPrice: 6,
    highPrice: 15,
  },
  {
    id: "me2-125",
    name: "Mega Charizard X ex",
    setName: "Phantasmal Flames",
    setId: "me2",
    numberLabel: "125/94",
    rarity: "Special Illustration Rare",
    imageUrl: art("me2", "125"),
    marketPrice: 155,
    lowPrice: 120,
    highPrice: 220,
    ask: 109,
    seller: "Binder Club",
  },
];

/** Shown on Values before someone searches. */
export const FEATURED_CARD_IDS = [
  "me2-125",
  "sv8pt5-161",
  "swsh7-215",
  "sv8-238",
  "base1-4",
  "sv10-231",
];

/** Chip order: the sets a parent is most likely to have in hand, then older chases. */
export const SET_ORDER = [
  "151",
  "Prismatic Evolutions",
  "Surging Sparks",
  "Destined Rivals",
  "Paldean Fates",
  "Obsidian Flames",
  "Phantasmal Flames",
  "Mega Evolution",
  "Evolving Skies",
  "Crown Zenith",
  "Vivid Voltage",
  "Base",
];
